modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ColorfulSkies/issues"
license="MIT"

[[mods]]
modId="colorfulskies"
version="${file.jarVersion}"
displayName="Colorful Skies"
displayURL="https://www.curseforge.com/minecraft/mc-mods/colorful-skies"
authors="Mrbysco"
description='''
Wait... The sky isn't supposed to be pink? Well, it is now!
'''
[[dependencies.colorfulskies]]
modId="minecraft"
type="required"
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"
[[dependencies.colorfulskies]]
modId="neoforge"
type="required"
versionRange="[21.0.0-beta,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="colorfulskies.mixins.json"